version: "3.8"
services:
  frontend:
    build: ./frontend
    image: navereni/forum-project-frontend:latest
    container_name: forum-project-frontend
    ports:
    - target: 5000
      published: 80
  backend:
    build: ./backend
    image: navereni/forum-project-backend:latest
    container_name: forum-project-backend
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    ports:
    - target: 5000
      published: 5000